spring.application.name=Proyecto_Ex1_S3_Guias_y_Transporte
server.port=8080

spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ruta que representa el EFS montado. En AWS puedes montar EFS en /mnt/efs/guias.
app.efs.path=/tmp/efs/guias

# S3 real: dejar false para probar local. En AWS cambiar a true y configurar bucket/region.
app.s3.enabled=false
app.s3.bucket=mi-bucket-guias
app.s3.region=us-east-1

# Validación simple para descarga. Debe venir header X-API-KEY.
app.api.key=duoc123
