services:
  transportista-service:
    build: ./transportista-service
    ports:
      - "8081:8081"
  guia-service:
    build: ./guia-service
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
      S3_BUCKET: cambia-este-bucket
      EFS_PATH: /mnt/efs/guias
    volumes:
      - ./efs-guias:/mnt/efs/guias
