spring.application.name=EX1_S3_Guias_Transporte
server.port=8080

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG


# Configuracion EFS
efs.path=/app/efs


# Bucket usado por los endpoints de guías. Se puede sobrescribir con variable de entorno AWS_S3_BUCKET.
aws.s3.bucket=${AWS_S3_BUCKET:guias-transporte-bucket}
