server.port=8080
spring.application.name=guia-service
spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
app.efs.path=${EFS_PATH:/mnt/efs/guias}
app.s3.bucket=${S3_BUCKET:guias-demo-bucket}
app.aws.region=${AWS_REGION:us-east-1}
